# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "coop.local"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    resources:
    - compress: false
      names:
      - client
      - federation
    tls: false
    type: http
    x_forwarded: true
database:
  name: psycopg2
  args:
    user: synapse
    password: synapse
    database: synapse
    host: synapse-db
    cp_min: 5
    cp_max: 10
log_config: "/data/coop.local.log.config"
media_store_path: /data/media_store
registration_shared_secret: "MpXnSpmsRzU1x=ALcdk2UB3hqv0w&x#^DCM^uFluG.Xly&@A0m"
report_stats: false
macaroon_secret_key: "7cfVIa6L9LcyDNkI8o-;v^WN5CSJ9Dqi0MTPdYr8oAEYvgtTnv"
form_secret: "PNKJD9Tj4EL6-CR^yL4iy&:AV-0VPF4w.K3T3@6k,_Ex;wOPnj"
signing_key_path: "/data/coop.local.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

enable_registration: true
enable_registration_without_verification: true

suppress_key_server_warning: true

# Disable rate limiting for local dev
rc_login:
  address:
    per_second: 100
    burst_count: 100
  account:
    per_second: 100
    burst_count: 100
  failed_attempts:
    per_second: 100
    burst_count: 100

rc_registration:
  per_second: 100
  burst_count: 100

rc_message:
  per_second: 100
  burst_count: 100

# vim:ft=yaml